language: python

python: "3.6"

install:
  - python setup.py install
  - pip install coverage codacy-coverage

script: coverage run --source music2storage setup.py test

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml